In [22]:
inputs = [[1, 2, 0]]
# Make 1 if the value is different from 0
mask = []   
for array in inputs:
    for value in array:
        if value != 0:
            mask.append(1)
        else:
            mask.append(0)

# mask = [1 if value != 0 else 0 for value for array for value in inputs] 
mask

[1, 1, 0]

In [25]:
import numpy as np

In [33]:
inputs = np.random.rand(10,3,3)
print(inputs)

inputs <=0.5

[[[0.19298032 0.0275345  0.13470674]
  [0.7222715  0.10293203 0.05072981]
  [0.09524935 0.33153456 0.68125095]]

 [[0.21361647 0.83643482 0.80547809]
  [0.48769668 0.84183323 0.60760382]
  [0.52913177 0.97927257 0.19733979]]

 [[0.10333041 0.13537016 0.18421593]
  [0.30859597 0.07956409 0.90366787]
  [0.82450769 0.60200629 0.45055839]]

 [[0.22266644 0.21820541 0.57300648]
  [0.39071856 0.21924684 0.7876582 ]
  [0.94193761 0.70020512 0.12586157]]

 [[0.86963385 0.28889522 0.7089219 ]
  [0.25376644 0.67798661 0.31377191]
  [0.12403897 0.39522474 0.85839919]]

 [[0.56502837 0.18018079 0.40041265]
  [0.00190887 0.03586261 0.53580906]
  [0.70474875 0.76477082 0.96799707]]

 [[0.59050385 0.32427692 0.10299547]
  [0.75937025 0.87483239 0.35105221]
  [0.34717919 0.41898159 0.26039138]]

 [[0.50193347 0.9639214  0.81296332]
  [0.12959042 0.35911971 0.35749363]
  [0.30919808 0.66483399 0.20519176]]

 [[0.74070819 0.1208674  0.66231914]
  [0.09059945 0.33903024 0.0152654 ]
  [0.47228301 0.481066

array([[[ True,  True,  True],
        [False,  True,  True],
        [ True,  True, False]],

       [[ True, False, False],
        [ True, False, False],
        [False, False,  True]],

       [[ True,  True,  True],
        [ True,  True, False],
        [False, False,  True]],

       [[ True,  True, False],
        [ True,  True, False],
        [False, False,  True]],

       [[False,  True, False],
        [ True, False,  True],
        [ True,  True, False]],

       [[False,  True,  True],
        [ True,  True, False],
        [False, False, False]],

       [[False,  True,  True],
        [False, False,  True],
        [ True,  True,  True]],

       [[False, False, False],
        [ True,  True,  True],
        [ True, False,  True]],

       [[False,  True, False],
        [ True,  True,  True],
        [ True,  True, False]],

       [[False, False, False],
        [ True, False, False],
        [False,  True,  True]]])